-- AlterTable
ALTER TABLE `user` ADD COLUMN `attention` INTEGER NULL DEFAULT 0,
    ADD COLUMN `birthday` VARCHAR(10) NULL,
    ADD COLUMN `city` VARCHAR(20) NULL,
    ADD COLUMN `company` VARCHAR(30) NULL,
    ADD COLUMN `education` INTEGER NULL DEFAULT 0,
    ADD COLUMN `fans` INTEGER NULL DEFAULT 0,
    ADD COLUMN `github` VARCHAR(100) NULL,
    ADD COLUMN `graduate_year` INTEGER NULL DEFAULT 1960,
    ADD COLUMN `integral` INTEGER NULL DEFAULT 0,
    ADD COLUMN `nickname` VARCHAR(10) NULL,
    ADD COLUMN `praise` INTEGER NULL DEFAULT 0,
    ADD COLUMN `rank` INTEGER NULL DEFAULT 0,
    ADD COLUMN `role` JSON NOT NULL;
